---

# Tasks to remove ansible-vagrant-box-prep

- name: Remove Vagrant public SSH key
  ansible.posix.authorized_key:
    user: vagrant
    state: absent
    key: https://raw.githubusercontent.com/hashicorp/vagrant/main/keys/vagrant.pub

- name: Remove NFS
  become: true
  when: python_selinux[ansible_os_family] not in ansible_facts.packages
  ansible.builtin.package:
    name: "{{ nfs_package[ansible_os_family] }}"
    state: absent

- name: Remove unused dependencies
  become: true
  ansible.builtin.package:
    autoremove: true

...
