---

# Runs all dependencies


- name: Install python3-selinux
  become: true
  when: python_selinux[ansible_os_family] not in ansible_facts.packages
  ansible.builtin.package:
    name: "{{ python_selinux[ansible_os_family] }}"
    state: present

...
