---

# tasks to install ansible-vagrant-box-prep


- name: Update package cache
  become: true
  ansible.builtin.package:
    update_cache: true
  changed_when: false

- name: Gather package facts
  ansible.builtin.package_facts:

- name: Include dependencies
  ansible.builtin.include_tasks:
    file: dependencies.yml

- name: Install Vagrant public SSH key
  ansible.posix.authorized_key:
    user: vagrant
    state: present
    key: https://raw.githubusercontent.com/hashicorp/vagrant/main/keys/vagrant.pub

- name: Install NFS
  become: true
  when: python_selinux[ansible_os_family] not in ansible_facts.packages
  ansible.builtin.package:
    name: "{{ nfs_package[ansible_os_family] }}"
    state: present

...
