---

- name: Verify
  hosts: client

  tasks:
    - name: Initialize role library
      ansible.builtin.include_role:
        name: ansible-vagrant-box-prep
        tasks_from: init

    - name: Gather package facts
      ansible.builtin.package_facts:

    - name: "Test for installed {{ python_selinux[ansible_os_family] }}"
      ansible.builtin.assert:
        that: python_selinux[ansible_os_family] in ansible_facts.packages
        fail_msg: "{{ python_selinux[ansible_os_family] }} not installed."
        quiet: true

    - name: "Test for installed {{ nfs_package[ansible_os_family] }}"
      ansible.builtin.assert:
        that: nfs_package[ansible_os_family] in ansible_facts.packages
        fail_msg: "{{ nfs_package[ansible_os_family] }} not installed."
        quiet: true

    - name: Download Vagrant public SSH key
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/hashicorp/vagrant/main/keys/vagrant.pub
        dest: /tmp/vagrant.pub
        mode: "0644"

    - name: Check if Vagrant public SSH key is installed in authorized_keys
      ansible.builtin.command:
        cmd: grep -f /tmp/vagrant.pub /home/vagrant/.ssh/authorized_keys
      register: vagrant_key_check
      changed_when: false
      failed_when: vagrant_key_check.rc != 0


    - name: Assert that Vagrant public SSH key matches
      ansible.builtin.assert:
        that:
          - vagrant_key_check.rc == 0
        fail_msg: "The Vagrant public SSH key was not found in the authorized_keys file"
        quiet: true

...
